sudo: required
services:
  - docker
# before_install:
#   - docker pull debian:jessie-slim
before_script:
  - wget -q https://bitbucket.org/matthewdalex/aarch64-linux-android-4.9/get/master.tar.gz
  - tar -xf master.tar.gz && rm master.tar.gz && ls
  - mv matthewdalex-aarch64-linux-android-4.9-4d5442c7c524 toolchain
script:
  - |
    docker run --rm -i --mount type=bind,src=`pwd`,target=/root ubuntu:18.04 bash << EOF
    apt-get -qq update
    apt-get -y --no-install-recommends install automake bc flex lzop bison gperf build-essential zip zlib1g-dev g++-multilib python-networkx libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev libmpfr6 libfl2 squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng
    ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4
    cd /root
    sed -i '/Werror /d' Makefile
    export ARCH=arm64 CROSS_COMPILE=/root/toolchain/bin/aarch64-linux-android-
    make clean && make j6lte_00_defconfig && make -j16
    exit
    EOF
# after_success:
#   - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
#   - cp $HOME/twrp/out/target/product/a6ltexx/recovery.img $HOME/twrp/TWRP-$version-a6ltexx-$(date +"%Y%m%d").img

# deploy:
#   skip_cleanup: true
#   provider: releases
#   api_key: "$GIT_OAUTH_TOKEN_TB"
#   file_glob: true
#   file: $HOME/twrp/*.img
#   on:
#     tags: false
#     repo: TwrpBuilder/android_device_samsung_a6ltexx
#     branch: master
# branches:
#   except:
# - /^(?i:untagged)-.*$/
